### ISSUE TITLE
Handling mixed type in a list

### ISSUE THREAD

**Issue by gedex** [jonasrichard/ejson#28]
Consider this case:

* Record `item`:

  ```
  #item{code :: string(), name :: string()}
  ```
* Record `error`:

   ```
  #error{code :: string(), message :: string()}
   ```
* List of items (that might have one or more errors in it):

  ```
  #items{items :: maybe_improper_list([] | #item{}, #error{})}
  ```

Is it possible to represent `#items{}` spec in `-json` attribute?

Here's the error that I got with similar record definitions above:

```
** exception error: bad argument
     in function  list_to_tuple/1
        called as list_to_tuple([item,0|{error,{no_value_for,{string,"code"}}}])
     in call from ejson_decode:decode1/3 (src/ejson_decode.erl, line 58)
     in call from ejson_decode:'-extract_list/3-lc$^0/1-0-'/3 (src/ejson_decode.erl, line 200)
     in call from ejson_decode:extract_list/3 (src/ejson_decode.erl, line 200)
     in call from ejson_decode:extract_fields/3 (src/ejson_decode.erl, line 87)
     in call from ejson_decode:decode1/3 (src/ejson_decode.erl, line 54)
     in call from ejson_decode:decode/3 (src/ejson_decode.erl, line 32)
     in call from wc_api:resp_to_coupon/3 (src/wc_api.erl, line 383)
```

**Comment by jonasrichard** [comment]
When I designed (and it was developed organically) two types of lists are born. Untyped and typed lists. 

In a typed list each element has the same (target) type. So when a json is generated, there are no __rec fields which describe the type of a record.

In an untyped list every type of record are possible, but in this case a __rec field is generated for each record (json object) in order that decoder can properly choose target type.

Can you send me a minimal code which reproduces the bug/question? It is good example to extend the documentation or fix a bug.

**Comment by gedex** [comment]
The error was thrown because the JSON to decode contains mixed type (as described above, item and error) but I defined `-json` attribute of the list with type `item`:

```
-json({items, {list, "items", [{type, item}]}}).
```

What would be the best why to handle this? I thought the only way would be to use `{post_decode, {?MODULE, from_jsx}` and do second decoding for each binary name/value pairs (element of list).

**Comment by jonasrichard** [comment]
I have just tested it works.

```erlang
-json({items, {list, "items"}}).
```

If you don't specify target types, any record can be in the list. But in this case a __rec field is generated for all objects in the list since the decoder needs to know the target type of the records in Erlang side.

See this test as an example.
https://github.com/jonasrichard/ejson/blob/27917c2b15d7a92c573f92969030d10317ca53e2/test/ejson_list_test.erl#L28

**Comment by jonasrichard** [comment]
If it solves your problem we can close this issue.

**Comment by gedex** [comment]
Hi @jonasrichard, sorry for late reply. I was overwhelmed with other things. I haven't tried it yet, but your comments clearly light my brain. I'll report another one in case I found another issue.

Cheers.
